x-keycloak-env: &kenv
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: passwd
  KC_DB: postgres
  KC_DB_URL_HOST: localhost
  KC_DB_URL_DATABASE: keycloak
  KC_DB_USERNAME: keycloak
  KC_DB_PASSWORD: passwd
  KC_HTTP_ENABLED: 'true'
  KC_HTTP_PORT: 3002
  KC_FEATURES: declarative-user-profile
  KC_SPI_THEME_STATIC_MAX_AGE: -1
  KC_SPI_THEME_CACHE_THEMES: 'false'
  KC_SPI_THEME_CACHE_TEMPLATES: 'false'
  KC_HOSTNAME: localhost
  KC_HOSTNAME_STRICT: 'false'
  KC_HOSTNAME_STRICT_HTTPS: 'false'
  JAVA_OPTS_APPEND: -Dquarkus.http.limits.max-initial-line-length=8192
services:
  postgresql:
    image: docker.io/library/postgres:15-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: keycloak
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 2s
      retries: 2
      start_period: 0s
    network_mode: host
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    entrypoint: ["/bin/bash", "-c"]
    # need to "build" first to make the image work with postgre db backend.
    command:
      - >
        /opt/keycloak/bin/kc.sh build --db=postgres --features=declarative-user-profile &&
        exec /opt/keycloak/bin/kc.sh start --optimized
    depends_on:
      postgresql:
        condition: service_started
    ports:
      - "3002:3002"
    environment:
      <<: *kenv
    volumes:
      - ./themes:/opt/keycloak/themes
      # - ./themes/base:/opt/keycloak/themes/base
      # - ./themes/base/common/resources/favicon.ico:/opt/keycloak/themes/base/common/resources/favicon.ico
      # - ./themes/base/common/resources/img/favicon.ico:/opt/keycloak/themes/base/common/resources/img/favicon.ico
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/$$KC_HTTP_PORT"]  # no curl in this image
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
    network_mode: host
  keycloak_init:
    image: quay.io/keycloak/keycloak:21.1
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      <<: *kenv
    volumes:
      - ./keycloak-init/:/keycloak-init/
    entrypoint: /keycloak-init/init.sh
    network_mode: host
  frontend:
    image: python:3-alpine
    working_dir: /app
    volumes:
      - .:/app/.:ro
    command: python -m http.server 8080 -b 127.0.0.1 -d .
    network_mode: host
volumes:
  postgresql_data:
    driver: local